version: "3"
services:
  cloudseed_app_env:
    build: ./App
    container_name: cloudseed_app
    depends_on:
      - cloudseed_development_database
    ports:
      - 5001:80
    environment:
      # Environment Variables set in App/appsettings.*.json
      ASPNETCORE_ENVIRONMENT: development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  cloudseed_development_database:
    build: ./DevelopmentDatabase
    restart: always
    ports:
      - 5002:5432
    environment:
      POSTGRES_PASSWORD: development_password
      POSTGRES_USER: cloudseed_database_user
  cloudseed_web:
    build: 
      context: ./Web
      dockerfile: ./dev.Dockerfile
    container_name: cloudseed_web
    ports:
      - 5000:8080
      - 24678:24678
    environment:
      # env vars set via dotfiles
      UNUSED_VARIABLE: UNUSED
    volumes:
      - ./Web:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
