version: "3"
services:
  cloudseed_app_env:
    build: ./App
    container_name: cloudseed
    depends_on:
      - cloudseed_development_database
    ports:
      - 5001:8080
    environment:
      # Environment Variables set in App/appsettings.*.json
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  cloudseed_development_database:
    build: ./DevelopmentDatabase
    restart: always
    ports:
      - 5002:5432
    environment:
      POSTGRES_PASSWORD: development_password
      POSTGRES_USER: cloudseed_database_user