version: "3"
services:
  cloudseed_app_tests:
    build: 
      context: ./
      dockerfile: ./test.Dockerfile
    container_name: cloudseed_app_tests
    # volumes:
    #   - .:/source
    #   - /etc/passwd:/etc/passwd:ro
    environment:
      # All environment variables available in appsettings.json
      ASPNETCORE_ENVIRONMENT: development
    depends_on:
      - cloudseed_db_test
    # command: "dotnet test --logger:trx"
  cloudseed_db_test:
    build: ./DevelopmentDatabase
    restart: always
    ports:
      - 5004:5432
    environment:
      POSTGRES_PASSWORD: development_password
      POSTGRES_USER: cloudseed_tests