version: "3"
services:
  cloudseed_app_env:
    build: ./App
    container_name: cloudseed_app
    depends_on:
      - cloudseed_development_database
    ports:
      - 5001:8080
    environment:
      ACCESS_TOKEN_COOKIE_NAME: CLOUDSEED_ACCESS_TOKEN
      DATABASE_HOST: cloudseed_development_database
      DATABASE_NAME: cloudseed
      DATABASE_PASSWORD: development_password
      DATABASE_USER: cloudseed_database_user
      EMAIL_FROM_ADDRESS: iamanemail
      JWT_SIGNING_KEY: "CHANGEMEiamasuperlongkeytosatisfythevlongrequirementsforthis123"
      POSTMARK_API_KEY: IAMAKEY
      STRIPE_API_KEY: IAMAKEY
      STRIPE_WEBHOOK_SECRET: iamakey
      WEB_BASE_URL: http://localhost:5000
      ASPNETCORE_ENVIRONMENT: development
  cloudseed_development_database:
    build: ./DevelopmentDatabase
    restart: always
    ports:
      - 5002:5432
    environment:
      POSTGRES_PASSWORD: development_password
      POSTGRES_USER: cloudseed_database_user
  cloudseed_web:
    build: 
      context: ./Web2
      dockerfile: ./dev.Dockerfile
    container_name: cloudseed_web
    ports:
      - 5000:8080
      - 24678:24678
    environment:
      # env vars set via dotfiles
      UNUSED_VARIABLE: UNUSED
    volumes:
      - ./Web2:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
